project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "qmd/*.qmd"

website:
  title: "Portfolio Personnel"
  site-url: "https://nevermind78.github.io/capstone_R/"
  repo-url: "https://github.com/nevermind78/capstone_R"
  repo-actions: [edit, issue]
  sidebar:
    style: docked
    search: true
    contents:
      - section: Projets
        contents:
          - qmd/projet1.qmd
          - qmd/projet2.qmd

format:
  html:
    theme: light
    css: thpe.css
    toc: true
    number-sections: true
    code-fold: true
    code-summary: "Afficher le code"
    code-link: true
    code-overflow: scroll
    lang: fr
  pdf:
    toc: false
    number-sections: true
    colorlinks: true
    papersize: a4
    geometry:
      - top=20mm
      - left=25mm
      - bottom=25mm

execute:
  freeze: auto
  cache: true
  echo: true
  warning: true
  message: false
  # Supprimez la section webr ci-dessous si vous ex√©cutez localement
  # webr:
  #   packages:
  #     - tidyverse
  #     - lubridate
  #     - ggplot2
  #     - plotly
  #     - DT
  #     - scales
  #     - corrplot
  #     - gridExtra
  #     - reshape2
  #     - knitr
  #     - kableExtra
  #     - readr
  #     - stringr
  #     - forcats
  #     - patchwork
  #     - readxl
  #     - dplyr
  #     - tidyr
  #     - car
  #     - lmtest
  #   show-startup-message: false
  #   emulate-r: true

bibliography: bib.bib
csl: apa.csl
latex-auto-install: true

metadata:
  lang: fr